name       : mullvad
version    : 2021.6
release    : 3
source     :
    - git|https://github.com/mullvad/mullvadvpn-app.git : 2021.6
license    : GPL-3.0-or-later
component  : network.clients
networking : yes
summary    : The Mullvad VPN client app for desktop
description: |
    The Mullvad VPN client app for desktop.
builddeps  :
    - pkgconfig(dbus-1)
    - cargo
    - git
    - golang
    - nodejs
setup      : |
    %apply_patches
build      : |
    ./build.sh
install    : |
    install -dm00755 $installdir/usr/share/mullvad
    cp -a dist/linux-unpacked/* $installdir/usr/share/mullvad

    install -Dm00755 dist-assets/mullvad $installdir/usr/bin/mullvad
    install -Dm00755 dist-assets/mullvad-exclude $installdir/usr/bin/mullvad-exclude

    install -Dm00644 $pkgfiles/mullvad-vpn.desktop $installdir/usr/share/applications/mullvad-vpn.desktop

    install -Dm00644 dist/linux-unpacked/resources/mullvad-daemon.service $installdir/%libdir%/systemd/system/mullvad-daemon.service
    sed -i 's/\/opt\/Mullvad\\x20VPN/\/usr\/share\/mullvad/g' $installdir/%libdir%/systemd/system/mullvad-daemon.service
