name       : mullvad
version    : 2022.5
release    : 7
source     :
    - git|https://github.com/mullvad/mullvadvpn-app.git : 2022.5
license    : GPL-3.0-or-later
component  : network.clients
networking : yes
summary    : The Mullvad VPN client app for desktop
description: |
    The Mullvad VPN client app for desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - cargo
    - git
    - golang
    - nodejs
rundeps    :
    - libayatana-appindicator
setup      : |
    %apply_patches
build      : |
    ./build.sh --optimize
install    : |
    install -dm00755 $installdir/usr/share/mullvad
    cp -a dist/linux-unpacked/* $installdir/usr/share/mullvad

    install -Dm00755 dist-assets/mullvad $installdir/usr/bin/mullvad
    install -Dm00755 dist-assets/mullvad-exclude $installdir/usr/bin/mullvad-exclude
    install -Dm00755 dist-assets/mullvad-daemon $installdir/usr/bin/mullvad-daemon

    install -Dm00644 $pkgfiles/mullvad-vpn.desktop $installdir/usr/share/applications/mullvad-vpn.desktop

    install -Dm00644 dist-assets/linux/mullvad-daemon.service $installdir/%libdir%/systemd/system/mullvad-daemon.service
    sed -i 's/\/opt\/Mullvad.*VPN/\/usr\/share\/mullvad/g' $installdir/%libdir%/systemd/system/mullvad-daemon.service
